---
- name: Ensure webroot exists
  file:
    path: "{{ letsencrypt_webroot_path }}"
    state: directory
    follow: yes
  become: yes

- name: Attempt to get the certificate using the webroot authenticator
  command: "{{ letsencrypt_command }} --webroot -w {{ letsencrypt_webroot_path }} certonly {% for domain in item %}-d {{ domain }} {% endfor %}"
  when: letsencrypt_authenticator == "webroot"
  ignore_errors: True
  with_items: "{{ letsencrypt_cert_domains }}"

- name: Attempt to get the certificate using the standalone authenticator (in case eg the webserver isn't running yet)
  command: "{{ letsencrypt_command }} -a standalone auth {% for domain in item %}-d {{ domain }} {% endfor %}"
  with_items: "{{ letsencrypt_cert_domains }}"
