---
  - name: Install depends
    apt: name={{ item }} state=installed
    with_items:
      - python
      - python-dev
      - python-virtualenv
      - gcc
      - dialog
      - libaugeas0
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - python-pip
      - git

  - name: Clone the repo
    git: repo=https://github.com/letsencrypt/letsencrypt dest={{ letsencrypt_install_directory }}
    notify:
      - Install letsencrypt

  - name: Install letsencrypt
    pip: chdir="{{ letsencrypt_install_directory }}" virtualenv="{{ letsencrypt_install_directory }}" virtualenv_site_packages=no requirements=requirements.txt

  - name: Get the certificate
    command: "{{ letsencrypt_install_directory }}/bin/letsencrypt {% if letsencrypt_agree_eula %}--agree-eula{% endif %} {% if letsencrypt_agree_tos %}--agree-tos{% endif %} --text --domains {{ letsencrypt_cert_domain }} {% if letsencrypt_email is defined %}--email {{ letsencrypt_email }} {% endif %}-a standalone auth"
    args:
      creates: "/etc/letsencrypt/live/{{ letsencrypt_cert_domain }}"
