---
  - name: Install depends
    apt: name={{ item }} state=installed
    with_items:
      - python
      - python-dev
      - python-virtualenv
      - gcc
      - dialog
      - libaugeas0
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - python-pip
      - git

  - name: Install python depends
    pip: virtualenv="{{ letsencrypt_venv }}" name={{ item }} state=latest
    with_items:
      - setuptools
      - pip

  - name: More python depends
    pip: virtualenv="{{ letsencrypt_venv }}" virtualenv_site_packages=no name={{ item }}
    with_items:
      - git+https://github.com/kuba/ConfigArgParse.git@python2.6-0.9.3#egg=ConfigArgParse
      - letsencrypt
      - letsencrypt-apache

  - name: Get the certificate
    command: "{{ letsencrypt_venv }}/bin/letsencrypt --agree-dev-preview {% if letsencrypt_agree_tos %}--agree-tos{% endif %} --text --domains {{ letsencrypt_cert_domain }} --email {{ letsencrypt_email }} -a standalone {% if letsencrypt_server is defined %}--server {{ letsencrypt_server }}{% endif %} auth"
    args:
      creates: "/etc/letsencrypt/live/{{ letsencrypt_cert_domain }}"
