---
  - name: Install depends
    apt: name={{ item }} state=installed
    with_items:
      - python
      - python-dev
      - python-virtualenv
      - gcc
      - dialog
      - libaugeas0
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - python-pip
      - git

  - name: Clone the repo
    git: repo=https://github.com/letsencrypt/letsencrypt dest={{ letsencrypt_src_directory }}

  - name: Install letsencrypt
    pip: chdir="{{ letsencrypt_src_directory }}" virtualenv="{{ letsencrypt_venv }}" virtualenv_site_packages=no name={{ item }} state=latest
    with_items:
      - letsencrypt
      - letsencrypt-apache
      - letsencrypt-nginx

  - name: Get the certificate
    command: "{{ letsencrypt_venv}}/bin/python {{ letsencrypt_venv }}/bin/letsencrypt --agree-dev-preview {% if letsencrypt_agree_tos %}--agree-tos{% endif %} --text --domains {{ letsencrypt_cert_domain }} --email {{ letsencrypt_email }} -a standalone auth"
    args:
      creates: "/etc/letsencrypt/live/{{ letsencrypt_cert_domain }}"
